name: Build Executables

on:
    push:
      branches:
        - use-importlib-resources  # Change this to the branch you want to run the workflow on
    pull_request:
      branches:
        - use-importlib-resources  # Change this to the branch you want to run the workflow on
  

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # specify the Python version you need

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --clean --onefile cookiecutter.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: cookiecutter-${{ runner.os }}
        path: dist/
