name: Build Executables

on:
    push:
      branches:
        - use-importlib-resources  # Change this to the branch you want to run the workflow on
    pull_request:
      branches:
        - use-importlib-resources  # Change this to the branch you want to run the workflow on
  

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # specify the Python version you need

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller cookiecutter.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: cookiecutter-${{ matrix.os }}
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: cookiecutter-ubuntu-latest.zip
        path: ./artifacts/ubuntu-latest
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: cookiecutter-macos-latest.zip
        path: ./artifacts/macos-latest
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: cookiecutter-windows-latest.zip
        path: ./artifacts/windows-latest

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.1.0  # Adjust the version number as needed
        release_name: Release v0.1.0
        body: |
          Pre-release version v0.1.0
        draft: true
        prerelease: false

    - name: Upload Release Asset (Ubuntu)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/ubuntu-latest/cookiecutter-ubuntu-latest.zip
        asset_name: cookiecutter-ubuntu-latest.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (macOS)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/macos-latest/cookiecutter-macos-latest.zip
        asset_name: cookiecutter-macos-latest.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (Windows)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/windows-latest/cookiecutter-windows-latest.zip
        asset_name: cookiecutter-windows-latest.zip
        asset_content_type: application/zip